### ISSUE TITLE
Incorrect symbol for 1FB24

### ISSUE THREAD

**Issue by ndevenish** [dokutan/legacy_computing-font#3]
As per https://en.wikipedia.org/wiki/Box-drawing_character this is supposed to be Sextant-236. Instead it is a duplicate of u+1Fb17 (Sextant-145).

I have highlighted the duplicate being demonstrated on the charmap.png shown in the README:
<img width="926" alt="image" src="https://github.com/dokutan/legacy_computing-font/assets/529963/ce3e97bb-2114-4c9a-9c35-202a74404cee">

**Comment by dokutan** [comment]
Thanks, i don't know how it this has gone unnoticed for over three years.

I have fixed this and made a new release: https://github.com/dokutan/legacy_computing-font/releases/tag/v1.1
