### ISSUE TITLE
Filecard (U+1FBB9 + U+1FBBA) should not look like a files folder.

### ISSUE THREAD

**Issue by PhMajerus** [dokutan/legacy_computing-font#4]
`U+1FBB9` and `U+1FBBA` are not supposed to represent a files folder, the Unicode naming is wrong.
They come from Apple II MouseText, and were originally designed to represent a Filecard.
Filecards are a legacy UI paradigm where the user would navigate menus as layers of cards containing menu items:

![image](https://github.com/user-attachments/assets/4213930a-f7c3-4a11-a3d3-0fd7ce920af5)

Each item on a card would either launch an action, using the running man ![image](https://github.com/user-attachments/assets/f4ec653c-a407-4741-9b77-d9234e566a4f) icon (`U+1FBB2` and `U+1FBB3`), or show another level of menu (like a cascading submenu in the newer GUI paradigms) using the Filecard ![image](https://github.com/user-attachments/assets/67ade3d5-5bc4-494f-9d53-27b24a74383c) icon.

Note how the cards do not have two pieces to contain files or subfolders, instead they look like stacks of organizer cards, and the icon represents a single card of that menu stack.

So the icon was designed on purpose to look like
![image](https://github.com/user-attachments/assets/4734eadb-dff3-4f0d-9bec-58a5ca27ec97)
instead of
![image](https://github.com/user-attachments/assets/ab392c87-45ef-421a-99be-2eadfc1e4d9b)

Here is the original Apple II version for reference:
![image](https://github.com/user-attachments/assets/a4caa008-e56d-480a-857f-b078ffea9323)

And here's Unicode's reference design:
![image](https://github.com/user-attachments/assets/d8908a1f-e468-44af-9bce-a2875c527800)

**Comment by dokutan** [comment]
Thank you for explaining the history of these characters, i have released version 1.2 where U+1FBB9 and U+1FBBA look like this:
![image](https://github.com/user-attachments/assets/6c1e3ad2-dff0-4c47-94ca-5f20f714cd9c)
